// <auto-generated>
//   This file was generated by generate_icon_keys.py
//   Generated: 2025-09-14 19:53:17
// </auto-generated>

using System;
using System.Collections.Generic;

namespace HYSoft.Presentation.Styles.Icons
{
    /// <summary>
    /// 아이콘 키 Enum (자동 생성)
    /// </summary>
    public enum EIconKeys
    {
        BluetoothDisabledRegular,
        BluetoothRegular,
        EditRegular
    }

    /// <summary>
    /// 아이콘 키 → 리소스 상대경로 매핑 (자동 생성)
    /// </summary>
    internal static class IconKeys
    {
        public static readonly Dictionary<EIconKeys, string> IconMap = new Dictionary<EIconKeys, string>
        {
            { EIconKeys.BluetoothDisabledRegular, "Icons/png/BluetoothDisabledRegular.png" },
            { EIconKeys.BluetoothRegular, "Icons/png/BluetoothRegular.png" },
            { EIconKeys.EditRegular, "Icons/png/EditRegular.png" }
        };
    }
}
